# Generated by Django 5.1.2 on 2024-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('tshirt', 'T-Shirt'), ('canvas', 'Canvas'), ('accessories', 'Accessories')], max_length=50)),
                ('design_details', models.TextField(help_text='Details about the desired design')),
                ('image', models.ImageField(blank=True, null=True, upload_to='order_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
